{% set name = "scrubadub_spacy" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LeapBeyond/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cd90477bc3f243d366e5eb8a3a443e58a97e3c1785dcfc4cf02742bc1a4a967e
  patches:
    - patches/0001-update-run.py.patch
    # Created an issue on these 2 failed tests.
    # https://github.com/LeapBeyond/scrubadub_spacy/issues/6
    - patches/0002-disabled-test_doc.patch
    - patches/0003-disabled-test_long_text.patch
    # tests failed on win by reason: python --version was unexpected at this time.
    # run nosetests ./tests/ without check on py35
    - patches/0004-change-py3-on-py-for-win-only.patch  # [win]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # https://github.com/AnacondaRecipes/spacy-transformers-feedstock/blob/master/recipe/meta.yaml#L21C1-L22C103
  # spacy-transformers is not avaliable on s390x
  skip: True  # [s390x]
  # spacy-transformers through spacy and pydantic <2.7.4 aren't compatible with python 3.12 currently
  skip: True  # [py>311]

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - scrubadub >=2.0.0rc0
    # https://github.com/LeapBeyond/scrubadub_spacy/blob/v2.0.0/requirements/python#L4
    # spacy[transformers]>=3.0.0
    - spacy >=3.0.0  # [py>=36]
    # spacy[transformers]>=3.0.0, needs transformers (from 'pip install --dry-run "spacy[transformers]>=3.0.0' output) -> transformers >=3.4.0,<4.37.0
    # Anaconda applies a patch and sets the transformers upper bound to <4.42.0 because of compatibility with 'tokenisers' versions
    - transformers >=3.4.0,<4.42.0  # [py>=36]
    # [E002] Can't find factory for 'curated_transformer' for language English (en)
    # ModuleNotFoundError: No module named 'spacy_transformers'
    # https://github.com/LeapBeyond/scrubadub_spacy/blob/v2.0.0/scrubadub_spacy/detectors/spacy.py#L176
    # spacy-transformers must be in the run dependency.
    - spacy-transformers <1.4.0

test:
  source_files:
    - tests
  imports:
    - scrubadub_spacy
  commands:
    - pip check
    # Test execution example
    # https://github.com/LeapBeyond/scrubadub_spacy/blob/v2.0.0/tox.ini#L17C5-L20C134
    - bash -c "python -m spacy info | grep Pipelines | grep -qv en_core_web_trf && python -m spacy download en_core_web_trf || exit 0"
    - bash -c "python -m spacy info | grep Pipelines | grep -qv en_core_web_sm && python -m spacy download en_core_web_sm || exit 0"
    - bash -c "python -m spacy info | grep Pipelines | grep -qv fr_core_news_lg && python -m spacy download fr_core_news_lg || exit 0"
    - bash -c "python -m spacy info | grep Pipelines | grep -qv de_core_news_sm && python -m spacy download de_core_news_sm || exit 0"
    - python tests/run.py
  requires:
    - pip
    - wasabi
    - nose

about:
  home: https://github.com/LeapBeyond/scrubadub_spacy
  summary: Use Spacy NER models to clean personally identifiable information from dirty dirty text.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    scrubadub removes personally identifiable information from text. scrubadub_spacy is an extension that uses spaCy NLP models to remove personal information from text.
    This package contains two extra detectors:
      scrubadub_spacy.detectors.SpacyEnityDetector - A detector that uses the spacy NER model to find locations, names, dates and other entities.
      scrubadub_spacy.detectors.SpacyNameDetector - A detector that uses the spacy NER model and context words to find names in text.
  doc_url: https://scrubadub.readthedocs.io/
  dev_url: https://github.com/LeapBeyond/scrubadub_spacy

extra:
  recipe-maintainers:
    - snegireff
